### ISSUE TITLE
Vertically scroll

### ISSUE THREAD

**Issue by ashrafdawoud** [oleksandrbalan/lazytable#14]
hi , have a problem when i try to scroll up or down with LazyTable it get me touch action and make scroll right or left , how can i solve this issue

**Comment by ashrafdawoud** [comment]
Uploading WhatsApp Video 2023-11-04 at 3.27.42 PM.mp4…

**Comment by ashrafdawoud** [comment]
Uploading WhatsApp Video 2023-11-04 at 3.27.42 PM.mp4…

**Comment by oleksandrbalan** [comment]
Hi 👋 

That's pretty interesting issue 🤔 
Could you please add a video of that behavior and/or probably some small reproduction sample? Also could you please specify on which platform dis you encounter this issue? Android, iOS or Desktop?
