### ISSUE TITLE
Support for `contentPadding`

### ISSUE THREAD

**Issue by Tgo1014** [oleksandrbalan/lazytable#2]
In my use case the table is full screen but as I've transparent navigation bars the table is displayed under the system bar. Would be nice if support for `contentPadding: PaddingValues` could be added so it can scroll from edge to edge.

**Comment by oleksandrbalan** [comment]
Released in [1.1.0](https://github.com/oleksandrbalan/lazytable/releases/tag/v1.1.0) 🎉
