### ISSUE TITLE
LazyTable and androidx.paging:paging-compose

### ISSUE THREAD

**Issue by leinardi** [oleksandrbalan/lazytable#21]
Hi, do you think it is possible to use `LazyTable` together with the official `androidx.paging:paging-compose` library?

We already use `androidx.paging:paging-compose` for normal `LazyColumn` and it would be great to be able to use it also with `LazyTable` since some of the table we need to display can have thousands of rows and fetching all the data at once isn't feasible.

**Comment by oleksandrbalan** [comment]
Recently I have added a sample with lazy loading in another issue. I guess it could be modified to work with `paging-compose` 👀 

https://github.com/oleksandrbalan/lazytable/issues/20#issuecomment-1910580538

**Comment by leinardi** [comment]
Hey thank you for the tip :slightly_smiling_face: 

We have actually tried to replace a `LazyColumn` with a `LazyTable` and it seems to work fine with `androidx.paging:paging-compose` (new pages get loaded when you scroll vertically). I'll re-open the ticket if we encounter issues related to this topic :+1:

**Comment by NikhilVSS** [comment]
@leinardi, @oleksandrbalan  can you provide an example, what changes you made, because I tried to integrate paging-compose with lazytable but was unable to do so ?

**Comment by NikhilVSS** [comment]
> @leinardi, @oleksandrbalan can you provide an example, what changes you made, because I tried to integrate paging-compose with lazytable but was unable to do so ?

never mind, there was a issue in PagingSource, lazytable worked like a charm 👍
