### ISSUE TITLE
Support wasm JS target

### ISSUE THREAD

**Issue by tylerwilson** [oleksandrbalan/lazytable#25]
Curious how hard supporting wasm JS target would be? I am currently using this control in Compose MP KMP library, and it is working well. But I would also like to support a wasm target, and since this is not supported in this library, I cannot yet either.

**Comment by oleksandrbalan** [comment]
Wasm support was added in [1.8.0](https://github.com/oleksandrbalan/lazytable/releases/tag/v1.8.0) 🥳 

https://github.com/oleksandrbalan/lazytable/assets/20944869/28da2e3a-fe02-4dfe-bbbf-29eab93a34bb
